---
name: Build Node.js images
on:
  workflow_dispatch:
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'
  push:
    paths:
      - 'node/**'
      - '.github/workflows/node.yaml'

jobs:

  targets:
    name: Get build targets
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.json.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - name: Generate JSON matrix
        id: json
        uses: docker/bake-action/subaction/matrix@v6
        with:
          files: node/docker-bake.hcl

  node:
    name: node
    needs: targets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}-${{ matrix.target }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.targets.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: muqtxdir
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: bake
        uses: docker/bake-action@v6
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        with:
          workdir: node
          source: .
          targets: ${{ matrix.target }}
          files: docker-bake.hcl
          push: ${{ github.ref_name == 'main' }}
          provenance: true
          sbom: true

      - name: Update Docker Hub Description
        if: github.ref_name == 'main' && matrix.target == 'node-25'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: muqtxdir
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: muqtxdir/node
          readme-filepath: ./node/README.md
